### ISSUE TITLE
Default authentication mode in `run_ydb.sh`

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/benchhelpers#6]
[Readme](https://github.com/ydb-platform/benchhelpers/blob/9926730447a842959bdbf17b45d54ab96bebe6ab/tpcc/ydb/README.md ) says
>  By default the `run_ydb.sh` uses anonymous authentication.

But it doesn't use it by default, you need `export YDB_ANONYMOUS_CREDENTIALS=1` to use it.

**Comment by eivanov89** [comment]
Thank you, it has been fixed in a recent version.
